### ISSUE TITLE
failure to demultiplex manifest

### ISSUE THREAD

**Issue by skurp** [aryeelab/guideseq#39]
Running test_manifest.yaml as well as the full_test.sh on the platform performs completely fine. My manifest file loads successfully (contains only a control and a single sample) and the demultiplexing process continues without error, however when UMI tagging begins I receive:

`[10/11 05:16:15PM][ERROR][guideseq] Error umitagging
[10/11 05:16:15PM][ERROR][guideseq] Traceback (most recent call last):
  File "guideseq/guideseq.py", line 150, in umitag
    os.path.join(self.output_folder, 'umitagged'))
  File "/projects/guideseq/guideseq/umi/umitag.py", line 56, in umitag
    for r1,r2,i1,i2 in itertools.izip(fq(read1), fq(read2), fq(index1), fq(index2)):
  File "/projects/guideseq/guideseq/umi/umitag.py", line 26, in fq
    fastq = open(file, 'r')
IOError: [Errno 2] No such file or directory: './run/output/demultiplexed/control.r1.fastq'`

Upon inspection of the demultiplexed output directory, there are almost 1500 files with names such as "AAGAGAAATCCTCT.i1.fastq" and the corresponding i2, r1, r2. It seems the true. error is occurring at the demultiplexing step. Any idea what is going on here?

Also, after the demultiplexing step the console outputs `Wrote FASTQs for the 357 sample barcodes out of 128400 with at least 1000 reads.`. However my manifest only contains 2 samples, including the control.

**Comment by vedtopkar** [comment]
Hey there,

Are you still having this problem? Would be curious to see your manifest file if so.

Thanks,
Ved

**Comment by mary30745** [comment]
Hi, did you somehow solve the problem with the demultiplexing process?
I have actually the same problem - In the "demultiplexed" folder, there are too many files named by nucleotide sequence... Do you have any idea how to fix it?
Thanks a lot

**Comment by Zethson** [comment]
Having the same issue. Anybody got any hints?

**Comment by mary30745** [comment]
Hey Zethson, 
what eventualy helped us was ramping up the demultiplex_min_reads number in the manifest way way higher (500 000, default was 1000). If that doesnt work, check if your index sequences in the manifest are correct (eg. not reverse complement, barcode1 is p7 index and not p5).  Good luck and let me know if it helped.

**Comment by motiar25** [comment]
Hi,
I trying to demultiplex but it is showing the following message. What might resolve the issue? Thank you.

Error demultiplexing reads.
[02/28 03:47:35PM][ERROR][guideseq] Traceback (most recent call last):
  File "/home/motiar25/anaconda3/envs/guideseq/lib/python3.8/site-packages/guide_seq-1.0.2-py3.8.egg/EGG-INFO/scripts/guideseq.py", line 141, in demultiplex
  File "/home/motiar25/anaconda3/envs/guideseq/lib/python3.8/site-packages/guide_seq-1.0.2-py3.8.egg/umi/demultiplex.py", line 102, in demultiplex
    outfiles_r2[sample_id] = open(os.path.join(out_dir, '%s.r2.fastq' % sample_id), 'w')
OSError: [Errno 24] Too many open files: '/mnt/c/Desktop/GuideSeqData/2E0/demultiplexed/CCTGAGACTTTCCC.r2.fastq'
