### ISSUE TITLE
Fastq downloaded from SRA showing error at identify off-targets step

### ISSUE THREAD

**Issue by asgarhussain** [aryeelab/guideseq#48]
I am able to align fastq file from SRA successfully. But I am getting following error at off-target step 

**[08/06 12:11:40PM][INFO][guideseq] Identifying offtarget sites...
[08/06 12:11:40PM][INFO][identifyOfftargetSites] Processing SAM file output1/aln1/aligned/SRR1695633_r1.sam
[08/06 12:11:40PM][ERROR][guideseq] Error identifying offtarget sites.
[08/06 12:11:40PM][ERROR][guideseq] Traceback (most recent call last):
  File "guideseq/guideseq.py", line 231, in identifyOfftargetSites
    identifyOfftargetSites.analyze(samfile, self.reference_genome, self.identified[sample], annotations)
  File "/home/asgar/asgar_work/dac/guideseq/guideseq/identifyOfftargetSites.py", line 217, in analyze
    chromosome_position.addPositionBarcode(chromosome, read_position, strand, barcode, primer, count)
  File "/home/asgar/asgar_work/dac/guideseq/guideseq/identifyOfftargetSites.py", line 66, in addPositionBarcode
    self.chromosome_barcode_dict[chromosome][position][strand][barcode] += count
TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'**

Does script not support the fastq file without bar code information ?

**Comment by madaojjc** [comment]
Hi, I met the same issue, have you ever solved it?  THANKS

**Comment by asgar-hussain** [comment]
@madaojjc They have not provided the bar code file in the SRA. I think off-target step can not run without it.

**Comment by wenhuihuang1979** [comment]
@asgar-hussain why? if not, how can we repeat their results?

**Comment by Bathroomboss** [comment]
The same question to you.  Can we get the "index reads" from SRA and repeat their results?
