### ISSUE TITLE
HTseq

### ISSUE THREAD

**Issue by mi32402** [aryeelab/guideseq#54]
I keep getting this error and cannot seem to fix this. Thoughts?

Traceback (most recent call last):
  File "guideseq/guideseq.py", line 22, in <module>
    from umi import demultiplex, umitag, consolidate
  File "/home/guideseq/guideseq/umi/consolidate.py", line 6, in <module>
    import HTSeq
  File "/home/.local/lib/python2.7/site-packages/HTSeq/__init__.py", line 12, in <module>
    raise ImportError( "Cannot import 'HTSeq' when working directory is HTSeq's own build directory.")
ImportError: Cannot import 'HTSeq' when working directory is HTSeq's own build directory.

**Comment by mi32402** [comment]
I keep getting this error and cannot seem to fix this. Thoughts?

Traceback (most recent call last):
  File "guideseq/guideseq.py", line 22, in <module>
    from umi import demultiplex, umitag, consolidate
  File "/home/guideseq/guideseq/umi/consolidate.py", line 6, in <module>
    import HTSeq
  File "/home/.local/lib/python2.7/site-packages/HTSeq/__init__.py", line 12, in <module>
    raise ImportError( "Cannot import 'HTSeq' when working directory is HTSeq's own build directory.")
ImportError: Cannot import 'HTSeq' when working directory is HTSeq's own build directory.
