### ISSUE TITLE
TypeError: load() missing 1 required positional argument: 'Loader'

### ISSUE THREAD

**Issue by mhtran145** [aryeelab/guideseq#69]
Hi, 
Could you please help me resolve this error? I have searched the web to troubleshoot it myself bu to no avail. Thank you very much in advance! 
(guideseq) mtran@MF18898 ~ % guideseq.py demultiplex -m /Users/mtran/Dropbox\ \(Scripps\ Research\)/GUIDE-seq/ITRseq_data/CSR20A-Ele64A/run_files/Ele20A_test1_manifest.yaml
[07/16 05:46:35PM][INFO][guideseq] Loading manifest for demultiplexing...
Traceback (most recent call last):
  File "/Users/mtran/opt/anaconda3/envs/guideseq/bin/guideseq.py", line 557, in <module>
    main()
  File "/Users/mtran/opt/anaconda3/envs/guideseq/bin/guideseq.py", line 438, in main
    g.parseManifestDemultiplex(args.manifest)
  File "/Users/mtran/opt/anaconda3/envs/guideseq/bin/guideseq.py", line 97, in parseManifestDemultiplex
    manifest_data = yaml.load(f)
TypeError: load() missing 1 required positional argument: 'Loader'

**Comment by mhtran145** [comment]
Hi again, 
I'm using the guideseq version from Tsai Lab.

**Comment by nechamaklt11** [comment]
Hello, encountered the same problem. Here is what worked for me:
changed the yaml.load(f) in the main guideseq.py script to yaml.full_load(f).
